import fs from "node:fs"
import {fileURLToPath} from "node:url"
import path from "node:path"

process.chdir(path.dirname(fileURLToPath(import.meta.url)))

const types = fs.readdirSync("project/export").filter(file => {
	return file.endsWith(".ts") && file !== "index.ts"
}).map(file => {
	return file.slice(0, -3)
}).toSorted((a, b) => {
	return a.localeCompare(b, "en")
})

let index = `// this file is automatically generated\n`

for (const type of types) {
	index += `export type {${type}} from "./${type}.ts"\n`
}

fs.writeFileSync(
	"project/export/index.ts", index
)
