// this file is automatically generated
export type {DropTupleElementsRight} from "./DropTupleElementsRight.ts"
export type {Literal} from "./Literal.ts"
export type {OnlyLiteral} from "./OnlyLiteral.ts"
export type {PopTuple} from "./PopTuple.ts"
export type {Primitive} from "./Primitive.ts"
export type {ReverseTuple} from "./ReverseTuple.ts"
export type {ShiftTuple} from "./ShiftTuple.ts"
export type {TupleOf} from "./TupleOf.ts"
